# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a Vector by Two
#'
#' Doubles each element of a numeric vector by passing the data into a
#' parallelized _C_ routine.
#'
#' @param x A `numeric` vector of values to multiply.
#' @param n The number of elements of `x` to process.
#'
#' @examples
#'
#' # Data
#' x = 1:5
#'
#' # Process all elements of x
#' n = length(x)
#'
#' # Call the routine
#' multiply_by_two(x, n = n)
#' @export
multiply_by_two <- function(x, n) {
    invisible(.Call(`_RcppCandOpenMP_multiply_by_two`, x, n))
}

