# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiple a Value By 2
#' 
#' Computes the multiplication of 2 by passing the data into a _C_ routine
#' that is parallelized
#' 
#' @param x A `vector` of numeric values to multiple.
#' @param n The number of cores to use.
#' 
#' @examples
#' 
#' # Data
#' x = 1:5
#' 
#' # Number of Cores to use in Parallelization
#' ncores = 2
#' 
#' # Call the routine
#' multiply_by_two(x, n = ncores)
#' @export
multiply_by_two <- function(x, n) {
    invisible(.Call(`_RcppCandOpenMP_multiply_by_two`, x, n))
}

